### ISSUE TITLE
Meta: Refactoring / fixing related to valid-object (VO) bit

### ISSUE THREAD

**Issue by wks** [mmtk/mmtk-core#804]
A previous attempt to address many of the following problems was unsuccessful.  https://github.com/mmtk/mmtk-core/pull/680

We should do the following one by one in separate PRs.

-   [X] **Renaming alloc bit to VO bit.** https://github.com/mmtk/mmtk-core/pull/791
-   [ ] **Add an API for explicitly clearing the VO bit.** https://github.com/mmtk/mmtk-core/issues/648
-   [ ] **Remove the `is_mmtk_object` feature.**  It should be enabled as long as VO bit is available.
-   [ ] **Refactor `vo_bit.rs`**
    -   Clean up the API, and only use `ObjectReference` (not `Address`) to access the VO bit.  This emphasises that VO bits are set at object references' raw addresses.
    -   Use `fetch_and` and `fetch_or` for atomic setting/clearing of bits.
-   [ ] **MarkCompactSpace shall use local bits.** It should use space-local allocation bits to identify objects.
-   [ ] **MallocSpace shall use local alloc bits.** Its semantics is different from VO bit.  Even after the VO bit is cleared, malloc MarkSweep still needs the alloc bit to identify objects allocated by `malloc`, and call `free` on them.
