### ISSUE TITLE
Checklist: Refactoring to be done after v0.19

### ISSUE THREAD

**Issue by wks** [mmtk/mmtk-core#921]
We bumped the Rust version to 1.71 in v0.19, and we may bump MSRV up to 1.70.  Some new features become available and existing code can be refactored to make use of those features.

-   [Generic Associated Types (GAT)](https://blog.rust-lang.org/2022/10/28/gats-stabilization.html): Stablised in Rust 1.65
    -   [ ] `vm::scanning::ObjectTracerContext` should use it instead of ignoring the lifetime.
-   [`std::array::from_fn`](https://doc.rust-lang.org/std/array/fn.from_fn.html): Stablised in Rust 1.63
    -   [ ] Replace `util::rust_util::array_from_fn`.
-   [`isize::wrapping_sub_unsigned`](https://doc.rust-lang.org/std/primitive.isize.html#method.wrapping_sub_unsigned): Stablised in 1.66
    -   [ ] Can be used in `util::alloc::allocator::align_allocation_inner`

**Comment by wks** [comment]
enum-map 2.7.0 introduced `EnumMap::from_fn(closure)` which makes `EnumMap::from_array(array_from_fn(closure))` useless.  We can remove `crate::util::rust_util::array_from_fn` completely.
